### ISSUE TITLE
Suggestion - skip mask characters on backspace

### ISSUE THREAD

**Issue by alaershov** [RedMadRobot/input-mask-android#14]
I have a question about edittext behavior when user tries to delete mask character, for example a brackedt or a whitespace in a phone number from the tutorial. Currently the cursor moves one character left, but does not actually delete anything.

`"+7 (999) 888 <cursor>77 66" -(backspace)>"+7 (999) 888<cursor> 77 66"`

I think this to be a bit counter-intuitive, and probably it would be better to delete the nearest user-typed character to the left of the cursor:

`"+7 (999) 888 <cursor>77 66" -(backspace)>"+7 (999) 88<cursor> 77 66"`

**Comment by taflanidi** [comment]
@alaershov the short answer is "No, we are not going to support such behaviour in the nearest future".

The main reason for this is the idea behind the logic of the library. User input processing is divided in two steps. 

During the first step, the library actually _allows_ user to make any corrections he wants to apply to the text. So when he presses `Backspace` having the cursor in pictured position

`+7 (999) 888 <cursor>77 66`

— he actually _deletes_ the space after `888` and the string becomes like this:

`+7 (999) 888<cursor>77 66`

Now, I want you to pay close attention to the cursor position, as the cursor stands after the **12th** symbol. Here, the second step is fired, when the formatting algorithm takes control over the flow.

This algorithm deals with a static data, which means it doesn't consider the way the input string was formed, but it do consider its state at the moment. Such that, the algorithm receives the actual string:

`+7 (999) 88877 66`

and the cursor position, which is **12**.

Dealing with a static data allowed us to make the formatting logic really simple and straightforward. In fact, all the magic happens in a single method, which doesn't [seem](https://github.com/RedMadRobot/input-mask-android/blob/master/inputmask/src/main/kotlin/com/redmadrobot/inputmask/helper/Mask.kt#L60) to be a God-like-single-long-piece-of-logic with hundreds of thousands of lines of code. Contrariwise, it is fairly compact.

It iterates over the format pattern and over the input string simultaneously, at each step making a decision, whether it should skip the input character or put it into the result string or put the character from the format pattern instead etc. You may say it tries to merge the pattern with the input.

In the meantime, cursor position falls under adjustments, too. When the algorithm puts some characters from its format pattern into the result string _before_ the cursor, the cursor position is increased. Otherwise, when some of the characters from the input string doesn't fit the pattern, they are skipped; when it happens _before_ the cursor, the cursor position is decreased. 

For instance, lets say the user pasted a phone number from the clipboard into the empty field:

`+7 999 888-77-66<cursor>` — cursor position is **16**

According to the pattern, the algorithm should:
* put **2** round brackets around the `999`
* remove **2** dashes in `888-77-66`
* put **2** spaces instead of dashes.

All these actions occur before the cursor, and in total the final cursor position is

`16 + 2 – 2 + 2 = 18`

which is exactly what we want:

`+7 (999) 888 77 66<cursor>` — cursor position is **18**.

The problem is, what happens when the algorithm puts new characters near the cursor?
Here, I'll give an example from your comment:

`+7 (999) 888<cursor>77 66` — it's the actual line the algorithm should deal with.

Remember I told that the algorithm doesn't consider the way the input string was formed? It's the main idea that made it so simple and "state-machine-like".

When formatting occurs, the logic can't define whether there was a character deletion before, or the user pasted a substring into the field. For instance, you may have two different transitions, see below.

**"The deletion"**. There was a string:

`+7 (999) 888 <cursor>77 66`

User hits `Backspace`:

`+7 (999) 888<cursor>77 66`

**"Pasting from clipboard"**. There was a string:

`+7 (999) <cursor>776 6`

User pastes `888`:

`+7 (999) 888<cursor>776 6`

Thus, in two different transitions the cursor appears in the same position between `888` and `77`. 
In the first situation, cursor position should be preserved, but in the second situation the algorithm should put a space before it:

`+7 (999) 888<cursor> 77 66`
vs.
`+7 (999) 888 <cursor>77 66`

We solved this with an assumption that the algorithm should _always_ put a character before the cursor, but when the deletion occurs, cursor position is [preserved](https://github.com/RedMadRobot/input-mask-android/blob/master/inputmask/src/main/kotlin/com/redmadrobot/inputmask/MaskedTextChangedListener.kt#L135) before the formatting magic is called. This was made the responsibility of the library's [TextWatcher](https://github.com/RedMadRobot/input-mask-android/blob/master/inputmask/src/main/kotlin/com/redmadrobot/inputmask/MaskedTextChangedListener.kt).

That said, right now there's simply no space for the behaviour you've mentioned.
Library's [TextWatcher](https://github.com/RedMadRobot/input-mask-android/blob/master/inputmask/src/main/kotlin/com/redmadrobot/inputmask/MaskedTextChangedListener.kt) doesn't have a clue about what characters behold to the user input, thus it can't decide whether it should delete an extra character on `Backspace` click.

Formatting algorithm doesn't have a clue about deletion or insertion; the only improvement I can see is to give it an "isDeletion" flag along with the input string and cursor position, but this change involves a lot of logic to be designed and implemented. 

Still, we are open for your pull requests as long as you retain the overall idea :D

**Comment by taflanidi** [comment]
P.s. For your manager you may say, that it's not a bug, but a feature :D Those spaces are not "magic gaps" between the user input fields for numbers, but they are the part of the text, too. 

Spaces are deleted by the user, and then they are returned back. But you may ensure that all the selected text in your input field might be copied correctly with no additional efforts to include "magic gaps" into the copied value.

**Comment by alaershov** [comment]
Now that was an extremely detailed answer! Thank you, I think I got the idea. It seems to me the question of approach to what the input mask actually is. My initial goal was to create a text field with "magic gaps", as you call them, and that's what made me start this issue.

**Comment by xanderblinov** [comment]
@alaershov please close issue if you have no question anymore ;)

**Comment by alaershov** [comment]
@xanderblinov Sorry, I thought that project members are responsible for closing issues. My bad)
