### ISSUE TITLE
android:inputType="number" get ERROR

### ISSUE THREAD

**Issue by yonathanbrazil** [RedMadRobot/input-mask-android#16]
I could simulate the EditText example but it work's if the input type is specifically **"text"** or **"phone"**.
As a number field I would like to restrict the keyboard to be only numeric, as a **android:inputType="number"**.
How can I do that?
Thnaks!

![mask_number](https://cloud.githubusercontent.com/assets/8696641/20486063/6d5b8dd6-afe5-11e6-9cad-2350f148b8c0.png)
![mask_phone](https://cloud.githubusercontent.com/assets/8696641/20486064/6d5df79c-afe5-11e6-89ad-5e00f11c1534.png)
![mask_text](https://cloud.githubusercontent.com/assets/8696641/20486065/6d5f16b8-afe5-11e6-9ae6-6af0bd0f73dc.png)

**Comment by taflanidi** [comment]
Hey @yonathanbrazil 

The library uses native `Editable` variable received on `afterTextChange` event in order to replace text efficiently. 

Because of that, field's `inputType` is actually considered when trying to mutate the text. 
SDK thinks that "numbers" cannot contain hyphens, dashes etc., which is pretty much accurate, to be honest.

Still, you can cheat by putting the "digits" value beside your inputType, where you can specify all the acceptable symbols:
```java
<EditText
    android:inputType="number"
    android:digits="0123456789 -."
    ...
```

**Comment by taflanidi** [comment]
Known issues section added.
