### ISSUE TITLE
question: How about paste into?

### ISSUE THREAD

**Issue by Rainer-Lang** [RedMadRobot/input-mask-android#26]

**Comment by taflanidi** [comment]
@Rainer-Lang, I'm sorry, what about it?

The library supports pasting text from clipboard. You may refer to [[some](https://github.com/RedMadRobot/input-mask-android/blob/master/inputmask/src/test/kotlin/com/redmadrobot/inputmask/helper/PhoneTest.kt#L441)] of [[our](https://github.com/RedMadRobot/input-mask-android/blob/master/inputmask/src/test/kotlin/com/redmadrobot/inputmask/helper/PhoneTest.kt#L495)] [[interesting](https://github.com/RedMadRobot/input-mask-android/blob/master/inputmask/src/test/kotlin/com/redmadrobot/inputmask/helper/PhoneTest.kt#L621)] [[test cases](https://github.com/RedMadRobot/input-mask-android/tree/master/inputmask/src/test/kotlin/com/redmadrobot/inputmask/helper)] in order to get yourself familiar with logic.

Please, provide additional information on your use case.

**Comment by Rainer-Lang** [comment]
I would use the pattern like "[AAA] - [AAA]", BUT for "A4E - 39W".
I have letters and numbers.
The letters should be converted to uppercase - via manually input and pasting.

What will happen if the user pastes:

- "G3R7E3"
- "G3R-7E3"
- "G3R - 7E3"
- "1234567890"
- "&$%123"
- ...

**Comment by taflanidi** [comment]
@Rainer-Lang, first of all, for the case when you have letters and digits mixed together I suggest you to use a `[___] - [___]` pattern. `_` stands for mandatory symbol (digit or letter).

Second, for `[___] - [___]` pattern the text will be formatted to:

- `G3R7E3` => `G3R - 7E3`
- `G3R-7E3` => `G3R - 7E3`
- `G3R - 7E3` => `G3R - 7E3`
- `1234567890` => `123 - 456`
- `&$%123` => `123` (in case, when autocomplete is not enabled; otherwise `123 - `).

**Comment by Rainer-Lang** [comment]
@taflanidi This is better than I thought! GREAT! :) 👍 
Thanks to make it clear. => closing this issue
