### ISSUE TITLE
Affine Masks problem

### ISSUE THREAD

**Issue by pdapnz** [RedMadRobot/input-mask-android#33]
Hi!

I try to implement universal TextEdit view using this library for phone entering. The idea is to change phone number mask dependent on  country code prefix, entered by user.

I define the masks patterns array
```
    private final static List<String> sAffineMasks = new ArrayList<String>() {
        {
            add("+1([000])[000]-[0000]");
            add("+20([000])[000]-[0000]");
            add("+27-[00]-[000]-[0000]");
            add("+30([000])[000]-[0000]");
            add("+31-[00]-[000]-[0000]");
            add("+49([000])[000]-[0000]");
//and other 100500 masks
```
And listener as described in readme:

```
        final MaskedTextChangedListener listener = new PolyMaskTextChangedListener(
                "+7([000])[000]-[00]-[00]",
                sAffineMasks,
                true,
                this,
                null,
                new MaskedTextChangedListener.ValueListener() {
                    @Override
                    public void onTextChanged(boolean maskFilled, @NonNull final String extractedValue) {
                        Timber.d(extractedValue);
                        Timber.d(String.valueOf(maskFilled));
                    }
                }
        );
```
Then I try this. I erase default mask start (+7) and try to type +1, as result I see +7(1. How can I fix this issue? 

Example from readme work fine.

**Comment by taflanidi** [comment]
Hi @pdapnz 
Thanks for your question. That is a bug, actually. My bad.

The problem is [here](https://github.com/RedMadRobot/input-mask-android/blob/master/inputmask/src/main/kotlin/com/redmadrobot/inputmask/PolyMaskTextChangedListener.kt#L139) — the `masks` variable is a list of (Mask, Affinity) pairs sorted by affinity, **ascending**. This means we really need the **last** element instead of the first.

I'll roll out a patch tomorrow. Please, stay tuned.

**Comment by pdapnz** [comment]
Hi! Is any news about this issue?

**Comment by taflanidi** [comment]
@pdapnz please try out the `2.3.0` version — I've published it to Bintray.
