### ISSUE TITLE
Clear EditText if value doesn't match mask

### ISSUE THREAD

**Issue by Juniornativa** [RedMadRobot/input-mask-android#34]
Hi! How can we clear EditText if value doesn't match the pattern? Thanks in advance!

**Comment by taflanidi** [comment]
Hey @Juniornativa! Thanks for your question. I'm not sure I've got it right, though.

If you need a check, whether your string matches the pattern or not — you should work with regular expressions. 

`Input Mask` library will always try to extract meaningful characters out of the input string instead of just giving a boolean answer "matches" or "not matches". For instance, if you've got a pattern like `1 (800) [000] [00] [00]` and a value `+1*8001234567` — the library will give you `1 (800) 123 45 67` as the answer.

If your value doesn't fit the pattern at all, you will end up with an empty string. For instance, in the situation when you are trying to put `abc` into the field with a `[000]` pattern. 

In addition, if your value matches the pattern partially but doesn't fill it, you may consider using the `maskFilled` boolean flag.

I hope this helps.
If it's not, please provide more details on what actually you are trying to achieve.
