### ISSUE TITLE
How can I set hint "telephone" until my edit text hasn't focus, or untill I dont click on my edit text???

### ISSUE THREAD

**Issue by serjTi** [RedMadRobot/input-mask-android#35]
Hi! Thank you for your library! I have a question! How can I set hint "telephone" until my edit text hasn't focus, or untill I dont click on my edit text???

**Comment by taflanidi** [comment]
Hi @serjTi! Thanks for your question.

I assume you are aware of the SDK [reference](https://developer.android.com/reference/android/widget/EditText.html) for the `EditText` component and its `setHint()` method in particular.

According to the README example, you may want to set a `MaskedTextChangedListener` instance as a `OnFocusChangeListener` for your text field by calling
```java
editText.setOnFocusChangeListener(listener);
```
— this way, you'll be able to use an "autocomplete" option whenever your text field gets focus in order to put prefix symbols before the user input.

First of all, **It's not a necessary call**. 
Second, you may want to track an `OnFocusChange` event by yourself AND have this functionality at the same time. 

In this case, I'd recommend you to implement a [decorator](https://en.wikipedia.org/wiki/Decorator_pattern) over the `MaskedTextChangedListener` instance with the interface of `OnFocusChangeListener` — and then put your decorator in place of the `OnFocusChangeListener`.

It looks like an overkill for a simple hint change, though.
