### ISSUE TITLE
Add smth like regex masking

### ISSUE THREAD

**Issue by adolgiy** [RedMadRobot/input-mask-android#45]
Hi, Robots! It will be cool, if library will offer something like regex filtering for cases, when I need to mask cardholder name. It's clear, that name and surname can be very short or long and developer can't predict lengths.

**Comment by taflanidi** [comment]
Hi @adolgiy!
Thanks for your question.

Could you please provide more case examples of the expected behaviour?

Right from your comment, I see no reason why you should use our library in the name fields of any kind. Cardholder name—as well as any other name—is just a simple alphabetic string, and possible restrictions on valid characters are applied by much more simple means than affinity-calculating-format-comparing-over-string-iterating masks like the one we've got here.

**Comment by adolgiy** [comment]
Hi @taflanidi! You're absolutely right, but this feature can help library users design EditTexts in the same way, because out-of-the-box library provides comfort interface to work with ETs.

**Comment by taflanidi** [comment]
@adolgiy,
Implemented in `3.2.0`.
See `Elliptical masks` for details.

**Comment by adolgiy** [comment]
Cool, thank you!
