### ISSUE TITLE
SetText inside TextWatcher Crashes

### ISSUE THREAD

**Issue by ahoefling** [RedMadRobot/input-mask-android#48]
This looks like a really promising plugin for a project I am working on but I need it to support deleting the gap. I found #14 where you document that this will not be supported which makes sense based on the explanation provided.

The api documentation states that the TextWatcher would be the appropriate place to do this and I have logic in place to get if we are doing a backspace and if the next set of chars is the gap. If this is the gap then it removes it and attempts to update the EditText by calling the SetText, but this throws an exception.

I had this working fine without the plugin but when I came across the plugin it seemed like a great way to clean up the masking code.

**Comment by taflanidi** [comment]
Hi @ahoefling,
Thanks for your question!

There are a few things you need to consider while implementing your gap-erasing behaviour.

Current `MaskedTextChangedListener` object—a `TextWatcher` implementation—has a two-step formatting algorithm, which includes capturing edited text & applying the mask in [`onTextChanged(text:cursorPosition:before:count:)`](https://github.com/RedMadRobot/input-mask-android/blob/master/inputmask/src/main/kotlin/com/redmadrobot/inputmask/MaskedTextChangedListener.kt#L122) and then returning formatted text back to the text field in [`afterTextChanged(edit:)`](https://github.com/RedMadRobot/input-mask-android/blob/master/inputmask/src/main/kotlin/com/redmadrobot/inputmask/MaskedTextChangedListener.kt#L110).

Because of this, `MaskedTextChangedListener` needs to preserve its [masked/formatted text](https://github.com/RedMadRobot/input-mask-android/blob/master/inputmask/src/main/kotlin/com/redmadrobot/inputmask/MaskedTextChangedListener.kt#L34) and corresponding [cursor position](https://github.com/RedMadRobot/input-mask-android/blob/master/inputmask/src/main/kotlin/com/redmadrobot/inputmask/MaskedTextChangedListener.kt#L35) between the steps. Formatted text and cursor position **must** remain consistent to each other, otherwise you may receive an out of range exception.

Thus, first of all, you should consider subclassing current `MaskedTextChangedListener` for your own `TextWatcher`—and use your tweaked version instead; second, you need to pay attention to its state.

If you don't mind, please share your implementation here, so that we could discuss the details without Chinese whispers.
