### ISSUE TITLE
Backspace button on number keyboard does not erase spaces and dashes correctly

### ISSUE THREAD

**Issue by madlabman** [RedMadRobot/input-mask-android#60]
I use that as part of `react-native-text-input-mask` library replacing implemented `2.3.0` version from VCS to your latest release (`3.4.4`). But both versions give me the same result. _On iOS same code works fine._ 

**Any idea?**

![backspace-input-mask](https://user-images.githubusercontent.com/10616301/44677406-e323b180-aa46-11e8-9529-4b831cd74131.gif)

**Comment by taflanidi** [comment]
Hi @madlabman!
Thanks for your question.

I ain't got no idea what actually happens under the hood of the React Native app shown on your GIF, I can only make a few guesses.

First of all, it clearly has something to do with `autocompletion`. So you may consider disabling it as an option.
Second, it feels like there are two listeners conflicting with each other. This might have happened due to React Native implicitly adding middleware `TextWatcher`s, but that's unlikely.
Third, _something_ is trying to modify the text through the text field's `setText(...)` instead of the `Editable` variable passed into the `TextWatcher`'s interface method.

FYI, I'm actually working on the «official» React Native port of our `InputMask` library. I just need to figure out some of the basics in order to get started, and then you may expect our support on the cross-platform basis.

**Comment by madlabman** [comment]
Thanks for your reply @taflanidi!

I set `autocompletion` option to false and fix my issue.
