### ISSUE TITLE
Keep Hint While Typing

### ISSUE THREAD

**Issue by MahdiAstanei** [RedMadRobot/input-mask-android#75]
It's not an issue but an enhancement, I need to keep hint behind text even while typing... I try to add it by my self but have no time for it.. can you do this for me?

**Comment by taflanidi** [comment]
Hi @MahdiAstanei,
Thanks for your suggestion. 

This doesn't go well with platform design guidelines, thus I'm not OK with adding this feature into the library, at least at the moment.

I'd rather recommend you to use solutions like the ones where character placeholders are filled with asterisks. There's a couple of libraries out there acting just like that.
```
(12*) ***-**-**
```
Otherwise, in case you do really have to stick with our library, the [`afterTextChanged`](https://github.com/RedMadRobot/input-mask-android/blob/master/inputmask/src/main/kotlin/com/redmadrobot/inputmask/MaskedTextChangedListener.kt#L171) method is your first candidate for adjustments. From there you may retrofit the `afterText` with the hint characters. Also consider getting rid of hint characters from `text` argument in [`onTextChanged`](https://github.com/RedMadRobot/input-mask-android/blob/master/inputmask/src/main/kotlin/com/redmadrobot/inputmask/MaskedTextChangedListener.kt#L183) method before picking the appropriate mask and before applying the format. This should do the trick.

**Comment by ddk9499** [comment]
Anyone implemented this feature? Can you share code, how to implement this? @MahdiAstanei

**Comment by GvinPin47** [comment]
> Anyone implemented this feature? Can you share code, how to implement this? @MahdiAstanei

It can be done without this library if cursor position handling not necessary you can do smth like this:

Create custom EditText and use onDraw method for drawing text on canvas, otherwise try @taflanidi suggestion
