### ISSUE TITLE
ERROR: Failed to resolve: com.redmadrobot:input-mask-android:4.2.0

### ISSUE THREAD

**Issue by haart28** [RedMadRobot/input-mask-android#83]
I have added the line 
implementation 'com.redmadrobot:input-mask-android:4.2.0'
to the 'app' module of my project, according to the latest docs.

What I get is:
"ERROR: Failed to resolve: com.redmadrobot:input-mask-android:4.2.0
Show in Project Structure dialog
Affected Modules: app"

Is it really available in jcenter now?

**Comment by taflanidi** [comment]
Hey @haart28!
Thanks a lot for your report. I'll look into this.

**Comment by taflanidi** [comment]
Okay, so it seems like we aren't moving to `input-mask-android` this time :D  
Maybe somewhere in the future, when the `5.0.0` comes out.

Please use the old 
```gradle
implementation 'com.redmadrobot:inputmask:4.2.0'
```
— it has all the updates, and I've already corrected our `README`.

Again, thank you for your assistance.
In case your problem is solved, please close this issue, or let me know if it's still not working for you.

**Comment by haart28** [comment]
Thank you for really quick response.
What I'm trying to achieve is to check new affinity mode - "capacity", introduced in 4.2.0. But unfortunately I have the same issue using implementation 'com.redmadrobot:inputmask:4.2.0' - ERROR: Failed to resolve: com.redmadrobot:inputmask:4.2.0
Only version 4.1.0 is worked for me.

**Comment by taflanidi** [comment]
@haart28,
Okay , I see. Me and my colleagues are working on this, please stay tuned for the updates!

**Comment by taflanidi** [comment]
Everything's back to normal, `4.3.0` is waiting for you to try it out.
