### ISSUE TITLE
Not changing mask

### ISSUE THREAD

**Issue by artmqq** [RedMadRobot/input-mask-android#84]
```
    private void setupPhoneMask(String mainMask) {

        phoneEditText.getEditText().setText(null);

        final List<String> affineFormats = new ArrayList<>();

        final MaskedTextChangedListener listener = MaskedTextChangedListener.Companion.installOn(
                phoneEditText.getEditText(),
                mainMask,
                affineFormats,
                AffinityCalculationStrategy.PREFIX,
                new MaskedTextChangedListener.ValueListener() {
                    @Override
                    public void onTextChanged(boolean maskFilled, @NonNull final String extractedValue, @NonNull String formattedText) {

                    }
                }
        );
        
        phoneEditText.getEditText().setHint(listener.placeholder());
    }
```
The first call setupPhoneMask ("+123 [00] [00] - [00] - [00]") - everything works.

When a user changes a country, I need to change the mask and I call up setupPhoneMask again, but with new masks. For example  ("+5 ([000]) - [00] - [00]"). 

Firstly, the +5 prefix is not added, and the field is completely empty(but new mask showing(hint)).
Secondly, if I enter for example 9, the result is not "+5 9", but "+5 (123) 9" and the cursor is between 2 and 3.

I apologize if this is not a bug and I just could not figure it out. Can you please tell me how to correctly change the mask?

**Comment by taflanidi** [comment]
Hey @artmqq!
Thanks for your question.

I'm sorry for this misunderstanding, I should've added this to the documentation. You see, the `installOn(…)` method internally adds a `MaskedTextChangedListener` instance as a `TextWatcher` by [calling](https://github.com/RedMadRobot/input-mask-android/blob/master/inputmask/src/main/kotlin/com/redmadrobot/inputmask/MaskedTextChangedListener.kt#L349) `addTextChangedListener(…)` on your `EditText`.

Thus, second time you call `installOn(…)` — it won't replace the previously installed `MaskedTextChangedListener`, but rather add another one, and they will most likely conflict with each other.

Unfortunately, there's no such thing as `remove_All_TextChangedListeners()` for the `EditText` class in the Android SDK, you've got to use the [`removeTextChangedListener(…)`](https://developer.android.com/reference/android/widget/TextView.html#removeTextChangedListener(android.text.TextWatcher)) method with a particular listener instance, so you'll have to retain the one returned after the `installOn(…)` call in order to replace it.

**Comment by artmqq** [comment]
Thank you, problem solved.

**Comment by Jahongirdevfromfergana** [comment]
hi
