### ISSUE TITLE
Combine digit mask and letter input

### ISSUE THREAD

**Issue by elvisfromsouth** [RedMadRobot/input-mask-android#86]
How can I combine mask for phone number and input letter, for example:
mask: +7 ([000]) [000]-[00]-[00]
input: 
7 -> +7
+79 -> +7 (9
+7 (9h -> 79h

**Comment by taflanidi** [comment]
Hey @elvisfromsouth,
Thanks for your question.

First of all, I'm not sure I've understood your requirements. Do you want to combine phone number text field to also be a "time" text field containing some number of hours? `79h`

Second, take a look at our wiki for the [affine masks](https://github.com/RedMadRobot/input-mask-android/wiki/2.1-Affine-Masks) — they might be of help.

**Comment by elvisfromsouth** [comment]
> Hey @elvisfromsouth,
> Thanks for your question.
> 
> First of all, I'm not sure I've understood your requirements. Do you want to combine phone number text field to also be a "time" text field containing some number of hours? `79h`
> 
> Second, take a look at our wiki for the [affine masks](https://github.com/RedMadRobot/input-mask-android/wiki/2.1-Affine-Masks) — they might be of help.

No, I need to use EditText for filter contact list. If I input only digits - search by phone number, if input letter - search by contact name.
I try to use Affine masks, but it is good works for only digits input. But when I combine letter mask and digit mask it is don't work... or I do a mistake...

**Comment by taflanidi** [comment]
Hey @elvisfromsouth!
Let me know what masks do you use. I guess, the first one would be
```
+7 ([000]) [000]-[00]-[00]
```
What are the others?

**Comment by elvisfromsouth** [comment]
@taflandi
I try to use some variants:
[...]
[A...]
[a...]

**Comment by elvisfromsouth** [comment]
@taflanidi 
I try to use some variants:
```[...]```
```[A...]```
```[a...]```

**Comment by taflanidi** [comment]
@elvisfromsouth,
Well, thanks to you, I've found a bug in our library. I'm going to issue an update.

Next, I'd like to propose this solution:
```java
final String symbols = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                     + "abcdefghijklmnopqrstuvwxyz"
                     + "АБВГДЕЁЖЗИКЛМНОПРСТУФХЦЧШЩЪЫЭЮЯ"
                     + "абвгдеёжзиклмнопрстуфхцчшщъыэюя"
                     + "+-()1234567890 ";

final List<Notation> customNotations = new ArrayList<>();
customNotations.add(new Notation('S', symbols, true));

final List<String> affineFormats = new ArrayList<>();
affineFormats.add("[S…]");

final MaskedTextChangedListener listener = MaskedTextChangedListener.Companion.installOn(
        editText,
        "+7 ([000]) [000]-[00]-[00]",
        affineFormats,
        customNotations,
        AffinityCalculationStrategy.PREFIX,
        true,
        null,
        new MaskedTextChangedListener.ValueListener() {
            @Override
            public void onTextChanged(boolean maskFilled, @NonNull final String extractedValue, @NonNull String formattedText) {
                logValueListener(maskFilled, extractedValue, formattedText);
                checkBox.setChecked(maskFilled);
            }
        }
);
```
— it utilises [custom notations](https://github.com/RedMadRobot/input-mask-android/wiki/1.1-Custom-Notations) along with affine masks' `AffinityCalculationStrategy`.

`AffinityCalculationStrategy.PREFIX` allows to switch between the available masks according to string prefixes. The list of masks contains:

```
+7 ([000]) [000]-[00]-[00]    -- the dominant/primary
[S…]                          -- the secondary
```

Secondary mask contains a predefined `S` notation, which represents all English and Russian letters, and also digits and phone number punctuation. Thus, the secondary mask accepts pretty much every character so that `MaskedTextChangedListener` will be able to switch from the primary mask to the secondary when user types
```
+7 (1d
```

The important note here is that I've found the ellipsis `…` character doesn't support custom notations in the Android version of our library, so I'll have to issue a patch in order to make both versions of the library even. This task is in progress right now.

**Comment by elvisfromsouth** [comment]
@taflanidi 
Perfect! Thanks for the help! =)
