### ISSUE TITLE
RTL Currency Input Mask

### ISSUE THREAD

**Issue by lucianocn** [RedMadRobot/input-mask-android#93]
Hi!  I would like to know if I can mask a currency input, using `Right to Left and Digit Grouping`, look like this:

*I appreciate if you can share an example.*

----------------

| Input       | Mask     | 
| :------------- | :----------: | 
| 1 | 0.01   | 
| 12   | 0.12 |
| 123   | 1.23 |
| 1234   | 12.34 |
| 12345   | 123.45 |
| 123456   | 1234.56 |

Thank you so much in advance!

**Comment by taflanidi** [comment]
Hey @lucianocn, thanks for your question!
I'll get back to this a little bit later during weekend. Please stay tuned.

**Comment by taflanidi** [comment]
Okay, @lucianocn, with our library there's no simple solution to achieve this requested behaviour.

In order to accommodate all the digits from the `123456` input there's got to be at least one affine mask with `6` or more places, say, `[0000].[00]`. 

Because of this mask, the algorithm will try to retain the prefixing zeros, as they are digits, too, meaning that you'll eventually end up with an output like

```
0001.23
```

From the library's perspective this is completely normal, the text is formatted according to the template, even if it's not a proper number.

You may try extending the existing `MaskedTextChangedListener` behaviour so that it will actually trim zeros, but then there's a situation you've got to handle when user hits backspace:

```
123.45
 12.34
  1.23
  0.12  <=  from here, you've got to add zeros _before_ the formatting occurs
  0.01
```

I'm suggesting you to write your own `TextWatcher` with a `NumberFormat` utility under the hood, or even better find an existing one. Our library still struggles with this feature, see #88.

**Comment by lucianocn** [comment]
@taflanidi thanks for your amazing answer!
I will write my own `TextWatcher` and keep you in touch with the news.

**Comment by taflanidi** [comment]
Understood.
Let me know if you need any help.
